baseURL = 'https://notes.adamangle.com/'
languageCode = 'en-us'
title = "Adam's Notes"
theme = 'notesTheme'

[params]
  creatorName = 'Adam Angle'
  contributeURL = 'https://github.com/adamangle/notes'
  customCSS = ['/font.css']

[menu]
  [[menu.main]]
    name = "Notes"
    pre = "pen-tool"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
